type Mutation {
  register(input: RegisterInput!): AuthResponse!
  login(input: LoginInput!): AuthResponse!
  logout: Boolean! # ログアウト
  resetPassword(input: ResetPasswordInput!): Boolean! # パスワードリセット
  verifyEmail(input: VerifyEmailInput!): Boolean! # メールアドレス確認
  deleteAccount: Boolean! # アカウントの非活性化
  refreshAccessToken(input: RefreshTokenInput): RefreshTokenResponse! # トークンのリフレッシュ
}

input RegisterInput {
  email: String!
  password: String!
  name: String!
}

input LoginInput {
  email: String!
  password: String!
}

input RefreshTokenInput {
  refreshToken: String!
}

type AuthResponse {
  token: String!
  user: User!
}

type RefreshTokenResponse {
  accessToken: String!
  refreshToken: String!
}
